### ISSUE TITLE
Line width not updating

### ISSUE THREAD

**Issue by booman81** [gpvigano/EasyCurvedLine#2]
![EasyCurvedLine_Bug](https://user-images.githubusercontent.com/16801270/106244650-e9b84380-6213-11eb-8f76-ea29612e03ba.gif)

EasyCurvedLine: Sep 15, 2020
Unity3D: 2019.3.11f1 Mac

Curved line Renderedr not effecting in real-time the Line Renderer. Tested with Auto Update enabled and disabled.
Example: Line Width property does not affect the line on the scene, The scene must be reloaded, and select the line again to view any changes.

**Comment by gpvigano** [comment]
Thank you for creating this issue and for the animated gif (very useful to quickly understand the problem).
The last commit (daf9628a65a72dc0a19576debd24459fe3715892) is a fix for this issue.
Please notice that now you can edit both the points in the Width curve graph (in LineRenderer component) and the corresponding fields in the CurvedLineRenderer component.
Also editing points in the middle of the curve seems to work (not available for older versions of Unity).
